CREATE TABLE IF NOT EXISTS harcosok (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nev VARCHAR(80) NOT NULL UNIQUE,
	letrehozas DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS kepessegek (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nev VARCHAR(200) NOT NULL UNIQUE,
    leiras VARCHAR(1000) NOT NULL,
    harcos_id INTEGER NOT NULL,
    FOREIGN KEY (harcos_id) REFERENCES harcosok(id)
);